// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type BlogDocumentDataSlicesSlice =
  | LabelsSlice
  | ContentWithImageSlice
  | OptionsContentSlice
  | IdeasSlice
  | ResumeBlogSlice;

/**
 * Content for blog documents
 */
interface BlogDocumentData {
  /**
   * title field in *blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * shortdescription field in *blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.shortdescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  shortdescription: prismic.RichTextField;

  /**
   * htmlcontent field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.htmlcontent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  htmlcontent: prismic.KeyTextField;

  /**
   * category field in *blog*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<
    | "Beneficios"
    | "Servicios Energica"
    | "Instalaciones"
    | "Optimización de flotas"
  >;

  /**
   * image field in *blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

type InstallpackagesDocumentDataSlicesSlice = PackagesSlice;

/**
 * Content for InstallPackages documents
 */
interface InstallpackagesDocumentData {
  /**
   * Slice Zone field in *InstallPackages*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: installpackages.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<InstallpackagesDocumentDataSlicesSlice> /**
   * Meta Title field in *InstallPackages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: installpackages.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *InstallPackages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: installpackages.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *InstallPackages*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: installpackages.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * InstallPackages document from Prismic
 *
 * - **API ID**: `installpackages`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InstallpackagesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<InstallpackagesDocumentData>,
    "installpackages",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | StepWizardSlice
  | ContactFormSlice
  | LabelsSlice
  | ResumeBlogSlice
  | CarrouselOptionsSlice
  | HeroSlice
  | IdeasSlice
  | OptionsContentSlice
  | ContentWithImageSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ProductsDocumentDataSlicesSlice = CarrouselOptionsSlice;

/**
 * Content for Products documents
 */
interface ProductsDocumentData {
  /**
   * Slice Zone field in *Products*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: products.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProductsDocumentDataSlicesSlice> /**
   * Meta Title field in *Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: products.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: products.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Products*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Products document from Prismic
 *
 * - **API ID**: `products`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProductsDocumentData>,
    "products",
    Lang
  >;

export type AllDocumentTypes =
  | BlogDocument
  | InstallpackagesDocument
  | PageDocument
  | ProductsDocument;

/**
 * Item in *CarrouselOptions → Default → Primary → options*
 */
export interface CarrouselOptionsSliceDefaultPrimaryOptionsItem {
  /**
   * IDdatabase field in *CarrouselOptions → Default → Primary → options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Id interno de la base de datos
   * - **API ID Path**: carrousel_options.default.primary.options[].iddatabase
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  iddatabase: prismic.KeyTextField;

  /**
   * image field in *CarrouselOptions → Default → Primary → options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.default.primary.options[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * textTopBanner field in *CarrouselOptions → Default → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.default.primary.options[].texttopbanner
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  texttopbanner: prismic.RichTextField;

  /**
   * hasTopBanner field in *CarrouselOptions → Default → Primary → options*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: carrousel_options.default.primary.options[].hastopbanner
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  hastopbanner: prismic.BooleanField;

  /**
   * brand field in *CarrouselOptions → Default → Primary → options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.default.primary.options[].brand
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  brand: prismic.KeyTextField;

  /**
   * capacity field in *CarrouselOptions → Default → Primary → options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.default.primary.options[].capacity
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  capacity: prismic.KeyTextField;

  /**
   * priceTopText field in *CarrouselOptions → Default → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.default.primary.options[].pricetoptext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  pricetoptext: prismic.RichTextField;

  /**
   * priceTopValue field in *CarrouselOptions → Default → Primary → options*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.default.primary.options[].pricetopvalue
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  pricetopvalue: prismic.NumberField;

  /**
   * priceBottomText field in *CarrouselOptions → Default → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.default.primary.options[].pricebottomtext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  pricebottomtext: prismic.RichTextField;

  /**
   * buttonText field in *CarrouselOptions → Default → Primary → options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.default.primary.options[].buttontext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontext: prismic.KeyTextField;

  /**
   * buttonLink field in *CarrouselOptions → Default → Primary → options*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.default.primary.options[].buttonlink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *CarrouselOptions → ExtendedOptions → Primary → options*
 */
export interface CarrouselOptionsSliceExtendedOptionsPrimaryOptionsItem {
  /**
   * image field in *CarrouselOptions → ExtendedOptions → Primary → options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.extendedOptions.primary.options[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * textTopBanner field in *CarrouselOptions → ExtendedOptions → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.extendedOptions.primary.options[].texttopbanner
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  texttopbanner: prismic.RichTextField;

  /**
   * hasTopBanner field in *CarrouselOptions → ExtendedOptions → Primary → options*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: carrousel_options.extendedOptions.primary.options[].hastopbanner
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  hastopbanner: prismic.BooleanField;

  /**
   * brand field in *CarrouselOptions → ExtendedOptions → Primary → options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.extendedOptions.primary.options[].brand
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  brand: prismic.KeyTextField;

  /**
   * capacity field in *CarrouselOptions → ExtendedOptions → Primary → options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.extendedOptions.primary.options[].capacity
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  capacity: prismic.KeyTextField;

  /**
   * priceTopText field in *CarrouselOptions → ExtendedOptions → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.extendedOptions.primary.options[].pricetoptext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  pricetoptext: prismic.RichTextField;

  /**
   * priceTopValue field in *CarrouselOptions → ExtendedOptions → Primary → options*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.extendedOptions.primary.options[].pricetopvalue
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  pricetopvalue: prismic.NumberField;

  /**
   * priceBottomText field in *CarrouselOptions → ExtendedOptions → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.extendedOptions.primary.options[].pricebottomtext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  pricebottomtext: prismic.RichTextField;

  /**
   * buttonText field in *CarrouselOptions → ExtendedOptions → Primary → options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.extendedOptions.primary.options[].buttontext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontext: prismic.KeyTextField;

  /**
   * buttonLink field in *CarrouselOptions → ExtendedOptions → Primary → options*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.extendedOptions.primary.options[].buttonlink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * buttonTwoText field in *CarrouselOptions → ExtendedOptions → Primary → options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.extendedOptions.primary.options[].buttontwotext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontwotext: prismic.KeyTextField;

  /**
   * buttonTwoLink field in *CarrouselOptions → ExtendedOptions → Primary → options*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.extendedOptions.primary.options[].buttontwolink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttontwolink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * htmlFeatures field in *CarrouselOptions → ExtendedOptions → Primary → options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.extendedOptions.primary.options[].htmlfeatures
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  htmlfeatures: prismic.KeyTextField;

  /**
   * InstallationIncluded field in *CarrouselOptions → ExtendedOptions → Primary → options*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: carrousel_options.extendedOptions.primary.options[].installationincluded
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  installationincluded: prismic.BooleanField;

  /**
   * IDdatabase field in *CarrouselOptions → ExtendedOptions → Primary → options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.extendedOptions.primary.options[].iddatabase
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  iddatabase: prismic.KeyTextField;
}

/**
 * Item in *CarrouselOptions → SimpleOptions → Primary → options*
 */
export interface CarrouselOptionsSliceSimpleOptionsPrimaryOptionsItem {
  /**
   * image field in *CarrouselOptions → SimpleOptions → Primary → options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.simpleOptions.primary.options[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * buttonText field in *CarrouselOptions → SimpleOptions → Primary → options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.simpleOptions.primary.options[].buttontext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontext: prismic.KeyTextField;

  /**
   * buttonLink field in *CarrouselOptions → SimpleOptions → Primary → options*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.simpleOptions.primary.options[].buttonlink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * title field in *CarrouselOptions → SimpleOptions → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.simpleOptions.primary.options[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Item in *CarrouselOptions → LogoList → Primary → options*
 */
export interface CarrouselOptionsSliceLogoListPrimaryOptionsItem {
  /**
   * image field in *CarrouselOptions → LogoList → Primary → options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.logoList.primary.options[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *CarrouselOptions → Default → Primary*
 */
export interface CarrouselOptionsSliceDefaultPrimary {
  /**
   * title field in *CarrouselOptions → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *CarrouselOptions → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * options field in *CarrouselOptions → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.default.primary.options[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  options: prismic.GroupField<
    Simplify<CarrouselOptionsSliceDefaultPrimaryOptionsItem>
  >;
}

/**
 * Default variation for CarrouselOptions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarrouselOptionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarrouselOptionsSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CarrouselOptions → ExtendedOptions → Primary*
 */
export interface CarrouselOptionsSliceExtendedOptionsPrimary {
  /**
   * title field in *CarrouselOptions → ExtendedOptions → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.extendedOptions.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *CarrouselOptions → ExtendedOptions → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.extendedOptions.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * options field in *CarrouselOptions → ExtendedOptions → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.extendedOptions.primary.options[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  options: prismic.GroupField<
    Simplify<CarrouselOptionsSliceExtendedOptionsPrimaryOptionsItem>
  >;
}

/**
 * ExtendedOptions variation for CarrouselOptions Slice
 *
 * - **API ID**: `extendedOptions`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarrouselOptionsSliceExtendedOptions = prismic.SharedSliceVariation<
  "extendedOptions",
  Simplify<CarrouselOptionsSliceExtendedOptionsPrimary>,
  never
>;

/**
 * Primary content in *CarrouselOptions → SimpleOptions → Primary*
 */
export interface CarrouselOptionsSliceSimpleOptionsPrimary {
  /**
   * options field in *CarrouselOptions → SimpleOptions → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.simpleOptions.primary.options[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  options: prismic.GroupField<
    Simplify<CarrouselOptionsSliceSimpleOptionsPrimaryOptionsItem>
  >;
}

/**
 * SimpleOptions variation for CarrouselOptions Slice
 *
 * - **API ID**: `simpleOptions`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarrouselOptionsSliceSimpleOptions = prismic.SharedSliceVariation<
  "simpleOptions",
  Simplify<CarrouselOptionsSliceSimpleOptionsPrimary>,
  never
>;

/**
 * Primary content in *CarrouselOptions → LogoList → Primary*
 */
export interface CarrouselOptionsSliceLogoListPrimary {
  /**
   * options field in *CarrouselOptions → LogoList → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel_options.logoList.primary.options[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  options: prismic.GroupField<
    Simplify<CarrouselOptionsSliceLogoListPrimaryOptionsItem>
  >;
}

/**
 * LogoList variation for CarrouselOptions Slice
 *
 * - **API ID**: `logoList`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarrouselOptionsSliceLogoList = prismic.SharedSliceVariation<
  "logoList",
  Simplify<CarrouselOptionsSliceLogoListPrimary>,
  never
>;

/**
 * Slice variation for *CarrouselOptions*
 */
type CarrouselOptionsSliceVariation =
  | CarrouselOptionsSliceDefault
  | CarrouselOptionsSliceExtendedOptions
  | CarrouselOptionsSliceSimpleOptions
  | CarrouselOptionsSliceLogoList;

/**
 * CarrouselOptions Shared Slice
 *
 * - **API ID**: `carrousel_options`
 * - **Description**: CarrouselOptions
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarrouselOptionsSlice = prismic.SharedSlice<
  "carrousel_options",
  CarrouselOptionsSliceVariation
>;

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * title field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * name field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * phone field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone: prismic.KeyTextField;

  /**
   * email field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * message field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.message
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  message: prismic.KeyTextField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ContactForm → GretaContactForm → Primary*
 */
export interface ContactFormSliceGretaContactFormPrimary {
  /**
   * title field in *ContactForm → GretaContactForm → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.gretaContactForm.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *ContactForm → GretaContactForm → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.gretaContactForm.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * company field in *ContactForm → GretaContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.gretaContactForm.primary.company
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;

  /**
   * name field in *ContactForm → GretaContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.gretaContactForm.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * phone field in *ContactForm → GretaContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.gretaContactForm.primary.phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone: prismic.KeyTextField;

  /**
   * email field in *ContactForm → GretaContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.gretaContactForm.primary.email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * numberOfVehicles field in *ContactForm → GretaContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.gretaContactForm.primary.numberofvehicles
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  numberofvehicles: prismic.KeyTextField;

  /**
   * message field in *ContactForm → GretaContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.gretaContactForm.primary.message
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  message: prismic.KeyTextField;
}

/**
 * GretaContactForm variation for ContactForm Slice
 *
 * - **API ID**: `gretaContactForm`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSliceGretaContactForm = prismic.SharedSliceVariation<
  "gretaContactForm",
  Simplify<ContactFormSliceGretaContactFormPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation =
  | ContactFormSliceDefault
  | ContactFormSliceGretaContactForm;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Item in *ContentWithImage → withIcons → Primary → list*
 */
export interface ContentWithImageSliceWithIconsPrimaryListItem {
  /**
   * ico field in *ContentWithImage → withIcons → Primary → list*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.withIcons.primary.list[].ico
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  ico: prismic.ImageField<never>;

  /**
   * title field in *ContentWithImage → withIcons → Primary → list*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.withIcons.primary.list[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *ContentWithImage → withIcons → Primary → list*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.withIcons.primary.list[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Item in *ContentWithImage → SmallImagesWithTitle → Primary → items*
 */
export interface ContentWithImageSliceSmallImagesWithTitlePrimaryItemsItem {
  /**
   * title field in *ContentWithImage → SmallImagesWithTitle → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.smallImagesWithTitle.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *ContentWithImage → SmallImagesWithTitle → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.smallImagesWithTitle.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * imageIsRight field in *ContentWithImage → SmallImagesWithTitle → Primary → items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: content_with_image.smallImagesWithTitle.primary.items[].imageisright
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  imageisright: prismic.BooleanField;

  /**
   * image field in *ContentWithImage → SmallImagesWithTitle → Primary → items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.smallImagesWithTitle.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *ContentWithImage → Default → Primary*
 */
export interface ContentWithImageSliceDefaultPrimary {
  /**
   * title field in *ContentWithImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *ContentWithImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * buttonOneText field in *ContentWithImage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.default.primary.buttononetext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttononetext: prismic.KeyTextField;

  /**
   * buttonOneLink field in *ContentWithImage → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.default.primary.buttononelink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttononelink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * buttonTwoText field in *ContentWithImage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.default.primary.buttontwotext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontwotext: prismic.KeyTextField;

  /**
   * buttonTwoLink field in *ContentWithImage → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.default.primary.buttontwolink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttontwolink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * imageIsRight field in *ContentWithImage → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: content_with_image.default.primary.imageisright
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  imageisright: prismic.BooleanField;

  /**
   * image field in *ContentWithImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ContentWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentWithImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentWithImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ContentWithImage → withIcons → Primary*
 */
export interface ContentWithImageSliceWithIconsPrimary {
  /**
   * title field in *ContentWithImage → withIcons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.withIcons.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *ContentWithImage → withIcons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.withIcons.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *ContentWithImage → withIcons → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.withIcons.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * imageIsRight field in *ContentWithImage → withIcons → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: content_with_image.withIcons.primary.imageisright
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  imageisright: prismic.BooleanField;

  /**
   * list field in *ContentWithImage → withIcons → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.withIcons.primary.list[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  list: prismic.GroupField<
    Simplify<ContentWithImageSliceWithIconsPrimaryListItem>
  >;

  /**
   * buttonText field in *ContentWithImage → withIcons → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.withIcons.primary.buttontext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontext: prismic.KeyTextField;

  /**
   * buttonLink field in *ContentWithImage → withIcons → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.withIcons.primary.buttonlink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * withIcons variation for ContentWithImage Slice
 *
 * - **API ID**: `withIcons`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentWithImageSliceWithIcons = prismic.SharedSliceVariation<
  "withIcons",
  Simplify<ContentWithImageSliceWithIconsPrimary>,
  never
>;

/**
 * Primary content in *ContentWithImage → HorizontalImage → Primary*
 */
export interface ContentWithImageSliceHorizontalImagePrimary {
  /**
   * title field in *ContentWithImage → HorizontalImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.horizontalImage.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *ContentWithImage → HorizontalImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.horizontalImage.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *ContentWithImage → HorizontalImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.horizontalImage.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * text01 field in *ContentWithImage → HorizontalImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.horizontalImage.primary.text01
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text01: prismic.RichTextField;

  /**
   * text02 field in *ContentWithImage → HorizontalImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.horizontalImage.primary.text02
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text02: prismic.RichTextField;

  /**
   * buttonOneText field in *ContentWithImage → HorizontalImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.horizontalImage.primary.buttononetext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttononetext: prismic.KeyTextField;

  /**
   * buttonOneLink field in *ContentWithImage → HorizontalImage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.horizontalImage.primary.buttononelink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttononelink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * buttonTwoText field in *ContentWithImage → HorizontalImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.horizontalImage.primary.buttontwotext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontwotext: prismic.KeyTextField;

  /**
   * buttonTwoLink field in *ContentWithImage → HorizontalImage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.horizontalImage.primary.buttontwolink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttontwolink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * HorizontalImage variation for ContentWithImage Slice
 *
 * - **API ID**: `horizontalImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentWithImageSliceHorizontalImage = prismic.SharedSliceVariation<
  "horizontalImage",
  Simplify<ContentWithImageSliceHorizontalImagePrimary>,
  never
>;

/**
 * Primary content in *ContentWithImage → SmallImagesWithTitle → Primary*
 */
export interface ContentWithImageSliceSmallImagesWithTitlePrimary {
  /**
   * title field in *ContentWithImage → SmallImagesWithTitle → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.smallImagesWithTitle.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *ContentWithImage → SmallImagesWithTitle → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.smallImagesWithTitle.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * items field in *ContentWithImage → SmallImagesWithTitle → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.smallImagesWithTitle.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<ContentWithImageSliceSmallImagesWithTitlePrimaryItemsItem>
  >;
}

/**
 * SmallImagesWithTitle variation for ContentWithImage Slice
 *
 * - **API ID**: `smallImagesWithTitle`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentWithImageSliceSmallImagesWithTitle =
  prismic.SharedSliceVariation<
    "smallImagesWithTitle",
    Simplify<ContentWithImageSliceSmallImagesWithTitlePrimary>,
    never
  >;

/**
 * Slice variation for *ContentWithImage*
 */
type ContentWithImageSliceVariation =
  | ContentWithImageSliceDefault
  | ContentWithImageSliceWithIcons
  | ContentWithImageSliceHorizontalImage
  | ContentWithImageSliceSmallImagesWithTitle;

/**
 * ContentWithImage Shared Slice
 *
 * - **API ID**: `content_with_image`
 * - **Description**: ContentWithImage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentWithImageSlice = prismic.SharedSlice<
  "content_with_image",
  ContentWithImageSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * buttonOneText field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttononetext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttononetext: prismic.KeyTextField;

  /**
   * buttonOneLink field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttononelink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttononelink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * buttonTwoText field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttontwotext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontwotext: prismic.KeyTextField;

  /**
   * buttonTwoLink field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttontwolink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttontwolink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → bgPrimary → Primary*
 */
export interface HeroSliceBgPrimaryPrimary {
  /**
   * title field in *Hero → bgPrimary → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.bgPrimary.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * image field in *Hero → bgPrimary → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.bgPrimary.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * buttonOneText field in *Hero → bgPrimary → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.bgPrimary.primary.buttononetext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttononetext: prismic.KeyTextField;

  /**
   * buttonOneLink field in *Hero → bgPrimary → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.bgPrimary.primary.buttononelink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttononelink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * buttonTwoText field in *Hero → bgPrimary → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.bgPrimary.primary.buttontwotext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontwotext: prismic.KeyTextField;

  /**
   * buttonTwoLink field in *Hero → bgPrimary → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.bgPrimary.primary.buttontwolink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttontwolink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * bgPrimary variation for Hero Slice
 *
 * - **API ID**: `bgPrimary`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceBgPrimary = prismic.SharedSliceVariation<
  "bgPrimary",
  Simplify<HeroSliceBgPrimaryPrimary>,
  never
>;

/**
 * Primary content in *Hero → blogHero → Primary*
 */
export interface HeroSliceBlogHeroPrimary {
  /**
   * title field in *Hero → blogHero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.blogHero.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * image field in *Hero → blogHero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.blogHero.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * buttonOneText field in *Hero → blogHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.blogHero.primary.buttononetext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttononetext: prismic.KeyTextField;

  /**
   * buttonOneLink field in *Hero → blogHero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.blogHero.primary.buttononelink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttononelink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * buttonTwoText field in *Hero → blogHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.blogHero.primary.buttontwotext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontwotext: prismic.KeyTextField;

  /**
   * buttonTwoLink field in *Hero → blogHero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.blogHero.primary.buttontwolink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttontwolink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * blogHero variation for Hero Slice
 *
 * - **API ID**: `blogHero`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceBlogHero = prismic.SharedSliceVariation<
  "blogHero",
  Simplify<HeroSliceBlogHeroPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceBgPrimary
  | HeroSliceBlogHero;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Ideas → Default → Primary*
 */
export interface IdeasSliceDefaultPrimary {
  /**
   * subTitle field in *Ideas → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ideas.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * title field in *Ideas → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ideas.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * buttonOneText field in *Ideas → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ideas.default.primary.buttononetext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttononetext: prismic.KeyTextField;

  /**
   * buttonOneLink field in *Ideas → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: ideas.default.primary.buttononelink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttononelink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * buttonTwoText field in *Ideas → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ideas.default.primary.buttontwotext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontwotext: prismic.KeyTextField;

  /**
   * buttonTwoLink field in *Ideas → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: ideas.default.primary.buttontwolink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttontwolink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Ideas Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IdeasSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IdeasSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Ideas*
 */
type IdeasSliceVariation = IdeasSliceDefault;

/**
 * Ideas Shared Slice
 *
 * - **API ID**: `ideas`
 * - **Description**: Ideas
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IdeasSlice = prismic.SharedSlice<"ideas", IdeasSliceVariation>;

/**
 * Item in *Labels → Default → Primary → list*
 */
export interface LabelsSliceDefaultPrimaryListItem {
  /**
   * link field in *Labels → Default → Primary → list*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: labels.default.primary.list[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Labels → Default → Primary*
 */
export interface LabelsSliceDefaultPrimary {
  /**
   * list field in *Labels → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: labels.default.primary.list[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  list: prismic.GroupField<Simplify<LabelsSliceDefaultPrimaryListItem>>;

  /**
   * title field in *Labels → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: labels.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for Labels Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LabelsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LabelsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Labels*
 */
type LabelsSliceVariation = LabelsSliceDefault;

/**
 * Labels Shared Slice
 *
 * - **API ID**: `labels`
 * - **Description**: Labels
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LabelsSlice = prismic.SharedSlice<"labels", LabelsSliceVariation>;

/**
 * Item in *OptionsContent → Default → Primary → options*
 */
export interface OptionsContentSliceDefaultPrimaryOptionsItem {
  /**
   * image field in *OptionsContent → Default → Primary → options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.default.primary.options[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *OptionsContent → Default → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.default.primary.options[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * textTopBanner field in *OptionsContent → Default → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.default.primary.options[].texttopbanner
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  texttopbanner: prismic.RichTextField;
}

/**
 * Item in *OptionsContent → TwoColumns → Primary → options*
 */
export interface OptionsContentSliceTwoColumnsPrimaryOptionsItem {
  /**
   * title field in *OptionsContent → TwoColumns → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.twoColumns.primary.options[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *OptionsContent → TwoColumns → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.twoColumns.primary.options[].subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * image field in *OptionsContent → TwoColumns → Primary → options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.twoColumns.primary.options[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * buttontext field in *OptionsContent → TwoColumns → Primary → options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.twoColumns.primary.options[].buttontext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontext: prismic.KeyTextField;

  /**
   * buttonlink field in *OptionsContent → TwoColumns → Primary → options*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.twoColumns.primary.options[].buttonlink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *OptionsContent → Founding team → Primary → options*
 */
export interface OptionsContentSliceFoundingTeamPrimaryOptionsItem {
  /**
   * image field in *OptionsContent → Founding team → Primary → options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.foundingTeam.primary.options[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * name field in *OptionsContent → Founding team → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.foundingTeam.primary.options[].name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * position field in *OptionsContent → Founding team → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.foundingTeam.primary.options[].position
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  position: prismic.RichTextField;

  /**
   * buttonLink field in *OptionsContent → Founding team → Primary → options*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.foundingTeam.primary.options[].buttonlink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * buttonImage field in *OptionsContent → Founding team → Primary → options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.foundingTeam.primary.options[].buttonimage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  buttonimage: prismic.ImageField<never>;
}

/**
 * Item in *OptionsContent → TwoColumnsText → Primary → options*
 */
export interface OptionsContentSliceTwoColumnsTextPrimaryOptionsItem {
  /**
   * image field in *OptionsContent → TwoColumnsText → Primary → options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.twoColumnsText.primary.options[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *OptionsContent → TwoColumnsText → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.twoColumnsText.primary.options[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *OptionsContent → TwoColumnsText → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.twoColumnsText.primary.options[].subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;
}

/**
 * Item in *OptionsContent → Team → Primary → options*
 */
export interface OptionsContentSliceTeamPrimaryOptionsItem {
  /**
   * image field in *OptionsContent → Team → Primary → options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.team.primary.options[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * name field in *OptionsContent → Team → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.team.primary.options[].name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * position field in *OptionsContent → Team → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.team.primary.options[].position
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  position: prismic.RichTextField;

  /**
   * buttonLink field in *OptionsContent → Team → Primary → options*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.team.primary.options[].buttonlink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * buttonImage field in *OptionsContent → Team → Primary → options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.team.primary.options[].buttonimage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  buttonimage: prismic.ImageField<never>;
}

/**
 * Primary content in *OptionsContent → Default → Primary*
 */
export interface OptionsContentSliceDefaultPrimary {
  /**
   * title field in *OptionsContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *OptionsContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * options field in *OptionsContent → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.default.primary.options[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  options: prismic.GroupField<
    Simplify<OptionsContentSliceDefaultPrimaryOptionsItem>
  >;
}

/**
 * Default variation for OptionsContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OptionsContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OptionsContentSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *OptionsContent → TwoColumns → Primary*
 */
export interface OptionsContentSliceTwoColumnsPrimary {
  /**
   * options field in *OptionsContent → TwoColumns → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.twoColumns.primary.options[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  options: prismic.GroupField<
    Simplify<OptionsContentSliceTwoColumnsPrimaryOptionsItem>
  >;
}

/**
 * TwoColumns variation for OptionsContent Slice
 *
 * - **API ID**: `twoColumns`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OptionsContentSliceTwoColumns = prismic.SharedSliceVariation<
  "twoColumns",
  Simplify<OptionsContentSliceTwoColumnsPrimary>,
  never
>;

/**
 * Primary content in *OptionsContent → Founding team → Primary*
 */
export interface OptionsContentSliceFoundingTeamPrimary {
  /**
   * title field in *OptionsContent → Founding team → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.foundingTeam.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *OptionsContent → Founding team → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.foundingTeam.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * options field in *OptionsContent → Founding team → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.foundingTeam.primary.options[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  options: prismic.GroupField<
    Simplify<OptionsContentSliceFoundingTeamPrimaryOptionsItem>
  >;
}

/**
 * Founding team variation for OptionsContent Slice
 *
 * - **API ID**: `foundingTeam`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OptionsContentSliceFoundingTeam = prismic.SharedSliceVariation<
  "foundingTeam",
  Simplify<OptionsContentSliceFoundingTeamPrimary>,
  never
>;

/**
 * Primary content in *OptionsContent → TwoColumnsText → Primary*
 */
export interface OptionsContentSliceTwoColumnsTextPrimary {
  /**
   * options field in *OptionsContent → TwoColumnsText → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.twoColumnsText.primary.options[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  options: prismic.GroupField<
    Simplify<OptionsContentSliceTwoColumnsTextPrimaryOptionsItem>
  >;

  /**
   * title field in *OptionsContent → TwoColumnsText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.twoColumnsText.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *OptionsContent → TwoColumnsText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.twoColumnsText.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * TwoColumnsText variation for OptionsContent Slice
 *
 * - **API ID**: `twoColumnsText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OptionsContentSliceTwoColumnsText = prismic.SharedSliceVariation<
  "twoColumnsText",
  Simplify<OptionsContentSliceTwoColumnsTextPrimary>,
  never
>;

/**
 * Primary content in *OptionsContent → Team → Primary*
 */
export interface OptionsContentSliceTeamPrimary {
  /**
   * title field in *OptionsContent → Team → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.team.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *OptionsContent → Team → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.team.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * options field in *OptionsContent → Team → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: options_content.team.primary.options[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  options: prismic.GroupField<
    Simplify<OptionsContentSliceTeamPrimaryOptionsItem>
  >;
}

/**
 * Team variation for OptionsContent Slice
 *
 * - **API ID**: `team`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OptionsContentSliceTeam = prismic.SharedSliceVariation<
  "team",
  Simplify<OptionsContentSliceTeamPrimary>,
  never
>;

/**
 * Slice variation for *OptionsContent*
 */
type OptionsContentSliceVariation =
  | OptionsContentSliceDefault
  | OptionsContentSliceTwoColumns
  | OptionsContentSliceFoundingTeam
  | OptionsContentSliceTwoColumnsText
  | OptionsContentSliceTeam;

/**
 * OptionsContent Shared Slice
 *
 * - **API ID**: `options_content`
 * - **Description**: OptionsContent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OptionsContentSlice = prismic.SharedSlice<
  "options_content",
  OptionsContentSliceVariation
>;

/**
 * Item in *Packages → Default → Primary → items*
 */
export interface PackagesSliceDefaultPrimaryItemsItem {
  /**
   * mts field in *Packages → Default → Primary → items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: packages.default.primary.items[].mts
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  mts: prismic.NumberField;

  /**
   * price35kW field in *Packages → Default → Primary → items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Valor para 3.5 kW
   * - **API ID Path**: packages.default.primary.items[].price35kw
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  price35kw: prismic.NumberField;

  /**
   * price7kW field in *Packages → Default → Primary → items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Valor
   * - **API ID Path**: packages.default.primary.items[].price7kw
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  price7kw: prismic.NumberField;
}

/**
 * Primary content in *Packages → Default → Primary*
 */
export interface PackagesSliceDefaultPrimary {
  /**
   * items field in *Packages → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: packages.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<PackagesSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Packages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PackagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PackagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Packages*
 */
type PackagesSliceVariation = PackagesSliceDefault;

/**
 * Packages Shared Slice
 *
 * - **API ID**: `packages`
 * - **Description**: Packages
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PackagesSlice = prismic.SharedSlice<
  "packages",
  PackagesSliceVariation
>;

/**
 * Item in *ResumeBlog → Default → Primary → options*
 */
export interface ResumeBlogSliceDefaultPrimaryOptionsItem {
  /**
   * image field in *ResumeBlog → Default → Primary → options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: resume_blog.default.primary.options[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *ResumeBlog → Default → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resume_blog.default.primary.options[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *ResumeBlog → Default → Primary → options*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resume_blog.default.primary.options[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * buttonText field in *ResumeBlog → Default → Primary → options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resume_blog.default.primary.options[].buttontext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontext: prismic.KeyTextField;

  /**
   * buttonLink field in *ResumeBlog → Default → Primary → options*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: resume_blog.default.primary.options[].buttonlink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *ResumeBlog → Default → Primary*
 */
export interface ResumeBlogSliceDefaultPrimary {
  /**
   * title field in *ResumeBlog → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resume_blog.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *ResumeBlog → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resume_blog.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * options field in *ResumeBlog → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: resume_blog.default.primary.options[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  options: prismic.GroupField<
    Simplify<ResumeBlogSliceDefaultPrimaryOptionsItem>
  >;
}

/**
 * Default variation for ResumeBlog Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResumeBlogSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ResumeBlogSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ResumeBlog*
 */
type ResumeBlogSliceVariation = ResumeBlogSliceDefault;

/**
 * ResumeBlog Shared Slice
 *
 * - **API ID**: `resume_blog`
 * - **Description**: ResumeBlog
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResumeBlogSlice = prismic.SharedSlice<
  "resume_blog",
  ResumeBlogSliceVariation
>;

/**
 * Item in *StepWizard → Default → Primary → steps*
 */
export interface StepWizardSliceDefaultPrimaryStepsItem {
  /**
   * number field in *StepWizard → Default → Primary → steps*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: step_wizard.default.primary.steps[].number
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  number: prismic.NumberField;

  /**
   * stepComponent field in *StepWizard → Default → Primary → steps*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: step_wizard.default.primary.steps[].stepcomponent
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  stepcomponent: prismic.NumberField;

  /**
   * title field in *StepWizard → Default → Primary → steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: step_wizard.default.primary.steps[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *StepWizard → Default → Primary → steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: step_wizard.default.primary.steps[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *StepWizard → Default → Primary*
 */
export interface StepWizardSliceDefaultPrimary {
  /**
   * installationIncluded field in *StepWizard → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: step_wizard.default.primary.installationincluded
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  installationincluded: prismic.BooleanField;

  /**
   * steps field in *StepWizard → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: step_wizard.default.primary.steps[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  steps: prismic.GroupField<Simplify<StepWizardSliceDefaultPrimaryStepsItem>>;
}

/**
 * Default variation for StepWizard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StepWizardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StepWizardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StepWizard*
 */
type StepWizardSliceVariation = StepWizardSliceDefault;

/**
 * StepWizard Shared Slice
 *
 * - **API ID**: `step_wizard`
 * - **Description**: StepWizard
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StepWizardSlice = prismic.SharedSlice<
  "step_wizard",
  StepWizardSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      InstallpackagesDocument,
      InstallpackagesDocumentData,
      InstallpackagesDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProductsDocument,
      ProductsDocumentData,
      ProductsDocumentDataSlicesSlice,
      AllDocumentTypes,
      CarrouselOptionsSlice,
      CarrouselOptionsSliceDefaultPrimaryOptionsItem,
      CarrouselOptionsSliceDefaultPrimary,
      CarrouselOptionsSliceExtendedOptionsPrimaryOptionsItem,
      CarrouselOptionsSliceExtendedOptionsPrimary,
      CarrouselOptionsSliceSimpleOptionsPrimaryOptionsItem,
      CarrouselOptionsSliceSimpleOptionsPrimary,
      CarrouselOptionsSliceLogoListPrimaryOptionsItem,
      CarrouselOptionsSliceLogoListPrimary,
      CarrouselOptionsSliceVariation,
      CarrouselOptionsSliceDefault,
      CarrouselOptionsSliceExtendedOptions,
      CarrouselOptionsSliceSimpleOptions,
      CarrouselOptionsSliceLogoList,
      ContactFormSlice,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceGretaContactFormPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      ContactFormSliceGretaContactForm,
      ContentWithImageSlice,
      ContentWithImageSliceDefaultPrimary,
      ContentWithImageSliceWithIconsPrimaryListItem,
      ContentWithImageSliceWithIconsPrimary,
      ContentWithImageSliceHorizontalImagePrimary,
      ContentWithImageSliceSmallImagesWithTitlePrimaryItemsItem,
      ContentWithImageSliceSmallImagesWithTitlePrimary,
      ContentWithImageSliceVariation,
      ContentWithImageSliceDefault,
      ContentWithImageSliceWithIcons,
      ContentWithImageSliceHorizontalImage,
      ContentWithImageSliceSmallImagesWithTitle,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceBgPrimaryPrimary,
      HeroSliceBlogHeroPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceBgPrimary,
      HeroSliceBlogHero,
      IdeasSlice,
      IdeasSliceDefaultPrimary,
      IdeasSliceVariation,
      IdeasSliceDefault,
      LabelsSlice,
      LabelsSliceDefaultPrimaryListItem,
      LabelsSliceDefaultPrimary,
      LabelsSliceVariation,
      LabelsSliceDefault,
      OptionsContentSlice,
      OptionsContentSliceDefaultPrimaryOptionsItem,
      OptionsContentSliceDefaultPrimary,
      OptionsContentSliceTwoColumnsPrimaryOptionsItem,
      OptionsContentSliceTwoColumnsPrimary,
      OptionsContentSliceFoundingTeamPrimaryOptionsItem,
      OptionsContentSliceFoundingTeamPrimary,
      OptionsContentSliceTwoColumnsTextPrimaryOptionsItem,
      OptionsContentSliceTwoColumnsTextPrimary,
      OptionsContentSliceTeamPrimaryOptionsItem,
      OptionsContentSliceTeamPrimary,
      OptionsContentSliceVariation,
      OptionsContentSliceDefault,
      OptionsContentSliceTwoColumns,
      OptionsContentSliceFoundingTeam,
      OptionsContentSliceTwoColumnsText,
      OptionsContentSliceTeam,
      PackagesSlice,
      PackagesSliceDefaultPrimaryItemsItem,
      PackagesSliceDefaultPrimary,
      PackagesSliceVariation,
      PackagesSliceDefault,
      ResumeBlogSlice,
      ResumeBlogSliceDefaultPrimaryOptionsItem,
      ResumeBlogSliceDefaultPrimary,
      ResumeBlogSliceVariation,
      ResumeBlogSliceDefault,
      StepWizardSlice,
      StepWizardSliceDefaultPrimaryStepsItem,
      StepWizardSliceDefaultPrimary,
      StepWizardSliceVariation,
      StepWizardSliceDefault,
    };
  }
}
