// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }


import React from "react";
import { Providers } from "@/store/providers";
import MyApp from "./app";
import PageContainer from '@/app/components/container/PageContainer';
import Banner from '@/app/components/shared/banner/Banner';
import HeaderAlert from '@/app/components/shared/header/HeaderAlert';
import HpHeader from '@/app/components/shared/header/HpHeader';
import Footer from '@/app/components/shared/footer';
import ScrollToTop from '@/app/components/shared/scroll-to-top';


import { configureAmplify } from "@/utils/amplify-config";
import GoogleAnalytics from "@/components/analytics/GoogleAnalytics";
import GoogleTagManager from "@/components/analytics/GoogleTagManager";
import GoogleTagManagerNoScript from "@/components/analytics/GoogleTagManagerNoScript";


import { Inter } from "next/font/google";
import { asText } from "@prismicio/client";
import { PrismicText } from "@prismicio/react";
import { PrismicNextLink, PrismicPreview } from "@prismicio/next";

import { createClient, repositoryName } from "@/prismicio";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});


// Configurar Amplify con la configuración del entorno correspondiente
configureAmplify();

export const metadata = {
  // title: "Instalación de cargadores para autos eléctricos",
  description: "Cotiza en tiempo real cuanto sale instalar el cargador de tu auto eléctrico. Simula tu proyecto y obtén una pre-cotización en segundos.",
  openGraph: {
    images: [
      {
        url: 'https://energica.city/hubfs/T%C3%A9cnico-instalador-1.png',
        width: 1200,
        height: 630,
        alt: 'Técnico instalador Energica',
      },
    ],
  },
};

// import { Amplify } from "aws-amplify";
// import outputs from "../../amplify_outputs.json";
// Amplify.configure(outputs);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" suppressHydrationWarning className={inter.variable}>
      <head>
        <GoogleTagManager />
        <GoogleAnalytics />
      </head>
      <body className="overflow-x-hidden antialiased">
        <GoogleTagManagerNoScript />
          <Providers>
            <MyApp>
              <PageContainer title="¡Hablemos!" description="Si quieres saber más de Enérgica City o lo que hacemos, conocer más de nuestros servicios para apoyar a tu empresa para dar el siguiente paso hacia la electromovilidad o simplemente cotizar, excríbenos un mensaje. Te responderemos lo antes posible.">
              {/* <HeaderAlert /> */}
              <HpHeader /> 
                {/* {children} */}
                <div className='isolate'>{children}</div>
                <Footer />
                <ScrollToTop />
              </PageContainer>
            </MyApp>
          <PrismicPreview repositoryName={repositoryName} />
        </Providers>
      </body>
    </html>
  );
}
