// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  carrousel_options: dynamic(() => import("./CarrouselOptions")),
  content_with_image: dynamic(() => import("./ContentWithImage")),
  hero: dynamic(() => import("./Hero")),
  ideas: dynamic(() => import("./Ideas")),
  labels: dynamic(() => import("./Labels")),
  options_content: dynamic(() => import("./OptionsContent")),
  resume_blog: dynamic(() => import("./ResumeBlog")),
};
